<a href="https://colab.research.google.com/github/Anshad-Aziz/technical-training/blob/main/House_prices_Model_Building.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [4]:
df=pd.read_csv('cleaned_data_for_model.csv')
df.head(2)

,Unnamed: 0,property_type,price,location,city,baths,purpose,bedrooms,Area_in_Marla
0,0,Flat,10000000,G-10,Islamabad,2,For Sale,2,4.0
1,1,Flat,6900000,E-11,Islamabad,3,For Sale,3,5.6

In [5]:

df.drop(['Unnamed: 0'],axis=1,inplace=True)
df.head()

,property_type,price,location,city,baths,purpose,bedrooms,Area_in_Marla
0,Flat,10000000,G-10,Islamabad,2,For Sale,2,4.0
1,Flat,6900000,E-11,Islamabad,3,For Sale,3,5.6
2,House,16500000,G-15,Islamabad,6,For Sale,5,8.0
3,House,43500000,Bani Gala,Islamabad,4,For Sale,4,40.0
4,House,7000000,DHA Defence,Islamabad,3,For Sale,3,8.0

In [6]:
x=df.drop(['price'],axis=1)
y=df.iloc[:,1:2]

In [7]:
x

,property_type,location,city,baths,purpose,bedrooms,Area_in_Marla
0,Flat,G-10,Islamabad,2,For Sale,2,4.0
1,Flat,E-11,Islamabad,3,For Sale,3,5.6
2,House,G-15,Islamabad,6,For Sale,5,8.0
3,House,Bani Gala,Islamabad,4,For Sale,4,40.0
4,House,DHA Defence,Islamabad,3,For Sale,3,8.0
...,...,...,...,...,...,...,...
77128,Lower Portion,I-8,Islamabad,3,For Rent,3,24.0
77129,Lower Portion,G-15,Islamabad,2,For Rent,2,8.0
77130,Upper Portion,I-8,Islamabad,3,For Rent,3,12.0
77131,House,Bahria Town Rawalpindi,Rawalpindi,4,For Sale,3,5.0
77132,House,Peshawar Road,Rawalpindi,5,For Sale,4,4.0

In [8]:
y

          price
0      10000000
1       6900000
2      16500000
3      43500000
4       7000000
...         ...
77128     75000
77129     30000
77130     70000
77131  10500000
77132  10000000

[77133 rows x 1 columns]

In [10]:
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0,1,2,4])],remainder='passthrough')
x=ct.fit_transform(x)

In [11]:
x

<77133x1392 sparse matrix of type '<class 'numpy.float64'>'
	with 539683 stored elements in Compressed Sparse Row format>

In [12]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [13]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()

model.fit(x_train,y_train)
prediction=model.predict(x_test)

In [14]:
linear_model=model.score(x_test,y_test)
print('Linear model score:',linear_model)

Linear model score: 0.6880563642868642

In [15]:
from sklearn import tree
dt_model=tree.DecisionTreeRegressor(criterion='squared_error',max_depth=3,max_leaf_nodes=5)
dt_model.fit(x_train,y_train)
dt_score=dt_model.score(x_test,y_test)
print('Decision Tree model score:',dt_score)

Decision Tree model score: 0.7256694503401127

In [17]:
from sklearn.ensemble import RandomForestRegressor
random_forest_model=RandomForestRegressor(n_estimators=10,
                                          criterion='squared_error',
                                          max_depth=5,
                                          min_samples_leaf=5,)
random_forest_model.fit(x_train,y_train)
random_forest_score=random_forest_model.score(x_test,y_test)
print('Random Forest score is:',random_forest_score)

<ipython-input-17-8e0a248cfa31>:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  random_forest_model.fit(x_train,y_train)

Random Forest score is: 0.7937144898615947

In [18]:
from sklearn.neighbors import KNeighborsRegressor
knn_model=KNeighborsRegressor(n_neighbors=5,
                              weights='distance')
knn_model.fit(x_train,y_train)
knn_score=knn_model.score(x_test,y_test)
print('KNN score:',knn_score)

KNN score: 0.8863664607378898

In [19]:
from sklearn.ensemble import GradientBoostingRegressor
gbm=GradientBoostingRegressor(learning_rate=1.0,
                              n_estimators=20,
                              max_depth=5,
                              min_samples_leaf=5)
gbm.fit(x_train,y_train)
gbs=gbm.score(x_test,y_test)
print('GRandient Boost Model Score:',gbs)

/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_gb.py:437: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GRandient Boost Model Score: 0.8757833685651163

In [20]:
import xgboost as xgb
xgb_model=xgb.XGBRegressor(objective='reg:linear',random_state=42)
xgb_model.fit(x_train,y_train)
xgb_score=xgb_model.score(x_test,y_test)
print('XG Boost Score:',xgb_score)

[13:44:59] WARNING: ../src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
XG Boost Score: 0.8970985428185709

In [21]:
from sklearn.ensemble import AdaBoostRegressor
adaboost_model=AdaBoostRegressor(n_estimators=20,
                                 learning_rate=0.1,
                                 loss='square')
adaboost_model.fit(x_train,y_train)
adaboost_score=adaboost_model.score(x_test,y_test)
print('ADA boost model score:',adaboost_score)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

ADA boost model score: 0.747493131129551

In [22]:
input_data=[['House','Wazir Town','Rawalpindi',4,'For Sale',3,165.9]]
input_data1=pd.DataFrame(input_data,columns=['property_type'	,'location',	'city'	,'baths'	,'purpose'	,'bedrooms',	'Area_in_Marla'])
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0,1,2,4])],remainder='passthrough')
input_data2=ct.fit_transform(input_data1)

input_data2

array([[  1. ,   1. ,   1. ,   1. ,   4. ,   3. , 165.9]])

In [23]:
import pickle
pickle.dump(knn_model,open('House_price_Prediction_with_knn.pk','wb'))

In [24]:
pickled_model=pickle.load(open('House_price_Prediction_with_knn.pk','rb'))
pickled_model.predict(x_test)

array([[14900000.],
       [ 5900000.],
       [20200000.],
       ...,
       [32700000.],
       [33400000.],
       [ 9600000.]])