<a href="https://colab.research.google.com/github/Anshad-Aziz/technical-training/blob/main/Machine_Learning(House_Price_2023.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [4]:
df=pd.read_csv('Cleaned_data_for_model.csv')
df.drop(['Unnamed: 0'],axis=1,inplace=True)
df.head()

,property_type,price,location,city,baths,purpose,bedrooms,Area_in_Marla
0,Flat,10000000,G-10,Islamabad,2,For Sale,2,4.0
1,Flat,6900000,E-11,Islamabad,3,For Sale,3,5.6
2,House,16500000,G-15,Islamabad,6,For Sale,5,8.0
3,House,43500000,Bani Gala,Islamabad,4,For Sale,4,40.0
4,House,7000000,DHA Defence,Islamabad,3,For Sale,3,8.0

In [5]:
x=df.drop(['price'],axis=1)
y=df.iloc[:,1:2]

In [6]:
x

,property_type,location,city,baths,purpose,bedrooms,Area_in_Marla
0,Flat,G-10,Islamabad,2,For Sale,2,4.0
1,Flat,E-11,Islamabad,3,For Sale,3,5.6
2,House,G-15,Islamabad,6,For Sale,5,8.0
3,House,Bani Gala,Islamabad,4,For Sale,4,40.0
4,House,DHA Defence,Islamabad,3,For Sale,3,8.0
...,...,...,...,...,...,...,...
99494,Flat,Bahria Town Karachi,Karachi,3,For Sale,3,8.0
99495,House,Bahria Town Karachi,Karachi,4,For Sale,3,8.0
99496,House,Bahria Town Karachi,Karachi,3,For Sale,3,8.0
99497,House,Bahria Town Karachi,Karachi,4,For Sale,4,14.0
99498,House,Bahria Town Karachi,Karachi,3,For Sale,3,9.4

In [7]:
y

          price
0      10000000
1       6900000
2      16500000
3      43500000
4       7000000
...         ...
99494   7500000
99495   8800000
99496  14000000
99497  14000000
99498   9000000

[99499 rows x 1 columns]

In [8]:
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0,1,2,4])],remainder='passthrough')
x=ct.fit_transform(x)

In [9]:
x

<99499x1406 sparse matrix of type '<class 'numpy.float64'>'
	with 696189 stored elements in Compressed Sparse Row format>

In [10]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [11]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(x_train,y_train)
prediction=model.predict(x_test)

linear_model=model.score(x_test,y_test)
print('Linear Model Score:',linear_model)

Linear Model Score: 0.695780839449085

In [13]:
from sklearn import tree
dt_model=tree.DecisionTreeRegressor(criterion='squared_error',max_depth=3,max_leaf_nodes=5)
dt_model.fit(x_train,y_train)
dt_score=dt_model.score(x_test,y_test)
print('Decision Tree model score:',dt_score)

Decision Tree model score: 0.7358533641982425

In [17]:
from sklearn.ensemble import RandomForestRegressor
random_forest_model=RandomForestRegressor(n_estimators=10,
                                          criterion='squared_error',
                                          max_depth=5,
                                          min_samples_leaf=5,)
random_forest_model.fit(x_train,y_train)
random_forest_score=random_forest_model.score(x_test,y_test)
print('Random forest score is :',random_forest_score)

<ipython-input-17-2d0530e91552>:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  random_forest_model.fit(x_train,y_train)

Random forest score is : 0.8159421038450302

In [19]:
from sklearn.neighbors import KNeighborsRegressor
knn_model=KNeighborsRegressor(n_neighbors=5,
                              weights='distance')
knn_model.fit(x_train,y_train)
knn_score=knn_model.score(x_test,y_test)
print('KNN score:',knn_score)

KNN score: 0.9039369844357242

In [23]:
from sklearn.ensemble import GradientBoostingRegressor
gradient_boost_model=GradientBoostingRegressor(learning_rate=1.0,
                                               n_estimators=20,
                                               max_depth=5,
                                               min_samples_leaf=5
                                               )
gradient_boost_model.fit(x_train,y_train)
gradient_boost_score=gradient_boost_model.score(x_test,y_test)
print('Gradient Boost Model Score:',gradient_boost_score)

/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_gb.py:437: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

Gradient Boost Model Score: 0.8819932376207069

In [28]:
import xgboost as xgb
xgb_model=xgb.XGBRegressor(objective='reg:linear',random_state=42)
xgb_model.fit(x_train,y_train)
xgb_score=xgb_model.score(x_test,y_test)
print('XG Boost score:',xgb_score)

[14:13:18] WARNING: ../src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
XG Boost score: 0.9047424403199563

In [29]:
from sklearn.ensemble import AdaBoostRegressor
adaboost_model=AdaBoostRegressor(n_estimators=20,
                                 learning_rate=0.1,
                                 loss='square')
adaboost_model.fit(x_train,y_train)
adaboost_score=adaboost_model.score(x_test,y_test)
print('ADA boost model score:',adaboost_score)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

ADA boost model score: 0.7610531428733506

In [32]:
#Prediction
input_data=[['House','Wazir Town','Rawalpindi',4,'For Sale',3,165.9]]
input_data1=pd.DataFrame(input_data,columns=['property_type'	,'location',	'city'	,'baths'	,'purpose'	,'bedrooms',	'Area_in_Marla'])
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0,1,2,4])],remainder='passthrough')
input_data2=ct.fit_transform(input_data1)

input_data2

array([[  1. ,   1. ,   1. ,   1. ,   4. ,   3. , 165.9]])

In [33]:
import pickle
pickle.dump(knn_model, open('House_Price_Prediction_with_KNN.pkl', 'wb'))

In [ ]:
pickled_model = pickle.load(open('House_Price_Prediction_with_KNN.pkl', 'rb'))
pickled_model.predict(x_test)